language: ruby
rvm: 2.3.5
gemfile:
  - Gemfile
sudo: false
before_install: gem install bundler
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
env:
  - RAILS_VERSION=5.1.4 RAILS_ENV=development
  - RAILS_VERSION=5.0.6 RAILS_ENV=development
  - RAILS_VERSION=4.1.16 RAILS_ENV=development
